// Run against a disposable local app. Exports images without creating accounts/posts.
import assert from 'node:assert/strict';
import fs from 'node:fs';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.argv[2] || 'http://127.0.0.1:5014';
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1360, height: 1000 } });
  page.setDefaultTimeout(120000);
  const errors = [], requests = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (['/convert', '/export'].includes(new URL(request.url()).pathname)) requests.push(request); });
  await page.addInitScript(() => {
    window.exportSettings = [];
    const fetch = window.fetch;
    window.fetch = (url, options) => {
      if (url === '/export' && options?.body instanceof FormData) {
        window.exportSettings.push(Object.fromEntries([...options.body].filter(([, value]) => typeof value === 'string')));
      }
      return fetch(url, options);
    };
  });
  assert.equal((await page.goto(`${base}/studio`)).status(), 200);
  assert.equal(await page.locator('#export-profile').inputValue(), 'standard');
  await page.locator('#file-input').setInputFiles('output/algorithm-comparison/illustrated/study-0-photo.jpg');
  await page.locator('#use-full-image-btn').click();
  await page.waitForFunction(() => document.querySelector('#live-text').textContent === 'Live');
  await page.locator('details.more').evaluate(el => { el.open = true; });
  const count = requests.length;
  await page.locator('#export-profile').selectOption('phone_tall');
  assert(await page.locator('#wallpaper-controls').isVisible());
  assert(await page.locator('#print-scale-control').isHidden());
  assert.equal(await page.locator('#wallpaper-preview').getAttribute('height'), '468');
  const whole = await page.locator('#wallpaper-preview').evaluate(canvas => canvas.toDataURL());
  await page.locator('#wallpaper-fit').selectOption('cover');
  assert.notEqual(await page.locator('#wallpaper-preview').evaluate(canvas => canvas.toDataURL()), whole);
  await page.locator('#wallpaper-fit').selectOption('contain');
  await page.locator('#color-amount-slider').fill('37');
  await page.waitForFunction(() => document.querySelector('#glyph-image').complete);
  assert.equal(requests.length, count, 'export settings and color slider must not render on the server');
  const downloadEvent = page.waitForEvent('download');
  const exportResponse = page.waitForResponse(response => new URL(response.url()).pathname === '/export');
  await page.locator('#download-image-btn').click();
  const download = await downloadEvent;
  assert.equal(download.suggestedFilename(), 'phone-wallpaper-2160x4680.png');
  assert.equal(await download.failure(), null);
  const response = await exportResponse;
  assert.equal(response.status(), 200);
  assert.equal(response.headers()['content-type'], 'image/png');
  const data = await page.evaluate(() => window.exportSettings.at(-1));
  assert.equal(data.color_amount, '0.37');
  assert.equal(data.wallpaper_fit, 'contain');
  fs.mkdirSync('output/wallpaper-study', { recursive: true });
  await download.saveAs('output/wallpaper-study/browser-phone.png');
  await page.waitForFunction(() => document.querySelector('#live-text').textContent === 'Live');
  assert.equal(await page.locator('#export-profile').inputValue(), 'phone_tall');
  const afterPrintCount = requests.length;
  await page.locator('#color-amount-slider').fill('80');
  assert.equal(requests.length, afterPrintCount, 'color stays instant after high-resolution export');
  await page.locator('#export-profile').selectOption('phone_classic');
  assert.equal(await page.locator('#wallpaper-preview').getAttribute('height'), '384');
  await page.locator('#export-profile').selectOption('maximum');
  assert(await page.locator('#wallpaper-controls').isHidden());
  assert.match(await page.locator('#export-hint').textContent(), /6,000/);
  await page.locator('#export-profile').selectOption('standard');
  assert(await page.locator('#print-scale-control').isVisible());
  const standardEvent = page.waitForEvent('download');
  await page.locator('#download-image-btn').click();
  const standard = await standardEvent;
  assert.equal(standard.suggestedFilename(), 'typewriter-drawing.png');
  assert.equal(await standard.failure(), null);
  await page.locator('#export-profile').selectOption('phone_tall');
  const changed = page.waitForResponse(response => new URL(response.url()).pathname === '/convert');
  await page.locator('#drawing-style').selectOption('original');
  await changed;
  await page.waitForFunction(() => document.querySelector('#live-text').textContent === 'Live');
  assert.equal(await page.locator('#export-profile').inputValue(), 'standard');
  assert(await page.locator('#export-profile option[value="maximum"]').isDisabled());
  const restored = page.waitForResponse(response => new URL(response.url()).pathname === '/convert');
  await page.locator('#drawing-style').selectOption('vibrant');
  await restored;
  await page.waitForFunction(() => document.querySelector('#live-text').textContent === 'Live');
  assert.equal(await page.locator('#export-profile').inputValue(), 'standard');
  await page.locator('#export-profile').selectOption('phone_tall');
  await page.locator('#wallpaper-preview').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'output/wallpaper-study/studio.jpg', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#wallpaper-preview').scrollIntoViewIfNeeded();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: 'output/wallpaper-study/mobile.jpg', fullPage: true });
  assert.deepEqual(errors, []);
  await page.reload();
  assert.equal(await page.locator('#export-profile').inputValue(), 'standard');
  console.log('PASS: opt-in only, live phone framing, both ratios, PNG download, color retained, standard/original behavior, mobile layout, no browser errors.');
} finally { await browser.close(); }
